name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REGION: us-central1  # Replace with your Artifact Registry region
      REPOSITORY_NAME: my-docker-repo  # Replace with your Artifact Registry repository name
      SERVICE_NAME: no-code-architects-toolkit  # Replace with your Cloud Run service name

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Validate Secrets
      run: |
        if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
          echo "Error: GCP_SA_KEY is not set." && exit 1
        fi
        if [ -z "${{ secrets.GCP_PROJECT_ID }}" ]; then
          echo "Error: GCP_PROJECT_ID is not set." && exit 1
        fi

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate Docker with Google Cloud
      run: |
        gcloud auth configure-docker --quiet

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:latest .
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:latest \
          --region $REGION \
          --platform managed
