name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Build and Push Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/no-code-architects-toolkit:patched .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/no-code-architects-toolkit:patched

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy <service-name> \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/no-code-architects-toolkit:patched \
          --region <your-region> \
          --platform managed
